In [2]:
import time
import numpy as np

In [7]:
n = 1_000_000

pyList = list(range(n))
numpyArr = np.arange(n)

print(len(pyList), len(numpyArr))
print(pyList[:5], numpyArr[:5])

1000000 1000000
[0, 1, 2, 3, 4] [0 1 2 3 4]


In [10]:
t1 = time.time()
pyResult = [x * 2 for x in pyList]
t2 = time.time()

t3 = time.time()
numpyResult = numpyArr * 2
t4 = time.time()

print(t2 - t1, t4 - t3)

0.07113242149353027 0.0028078556060791016


In [21]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr1[0,1])
print(arr1[1])
print(arr1[:, 1])

[[1 2 3]
 [4 5 6]]
2
[4 5 6]
[2 5]


In [22]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)

(2, 3)
2
int64
6


In [ ]:
zeros = np.zeros((3,3))
randomArr = np.random.rand(3, 3)
eye = np.eye(3)
rangeArr = np.arange(0, 10, 2)

print(zeros, randomArr, eye, rangeArr, sep="\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [23]:
%whos

Variable      Type       Data/Info
----------------------------------
arr1          ndarray    2x3: 6 elems, type `int64`, 48 bytes
eye           ndarray    3x3: 9 elems, type `float64`, 72 bytes
n             int        1000000
np            module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
numpyArr      ndarray    1000000: 1000000 elems, type `int64`, 8000000 bytes (7.62939453125 Mb)
numpyResult   ndarray    1000000: 1000000 elems, type `int64`, 8000000 bytes (7.62939453125 Mb)
pyList        list       n=1000000
pyResult      list       n=1000000
randomArr     ndarray    3x3: 9 elems, type `float64`, 72 bytes
rangeArr      ndarray    5: 5 elems, type `int64`, 40 bytes
t1            float      1778163906.4391599
t2            float      1778163906.5102923
t3            float      1778163906.5103219
t4            float      1778163906.5131297
time          module     <module 'time' (built-in)>
zeros         ndarray    3x3: 9 elems, type `float64`, 72 bytes


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.dot(a, b))
print(np.cross(a, b))

[5 7 9]
[ 4 10 18]
32
[-3  6 -3]


In [34]:
reshaped = arr1.reshape(3, 2)
print(arr1, reshaped, sep= "\n")

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
